services:
  backend:
    build: ./backend
    ports:
      - "1200:5000"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend/client
    ports:
      - "1201:3000"
    volumes:
      - ./frontend/client:/app
      - /app/node_modules
    depends_on:
      - backend 